name: 'SSM Parameter Store Env Loader'
description: 'Load environment variables from AWS SSM Parameter Store'
inputs:
  aws-role-to-assume:
    description: 'AWS role to assume for SSM access'
    required: false
  aws-region:
    description: 'AWS region for SSM access'
    required: false
    default: ap-northeast-2
  aws-path:
    required: true
    description: 'AWS SSM base path'


runs:
  using: node20
  main: 'dist/main.js'
